// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhHsbuT8vt4plKkY6Cdo69dmx8Kdq4mqY',
    appId: '1:314229576163:android:ad20ebe6a390e1e34690d6',
    messagingSenderId: '314229576163',
    projectId: 'il-tris-pizzeria-ds',
    databaseURL: 'https://il-tris-pizzeria-ds-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'il-tris-pizzeria-ds.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDXY4Tdxd3XrGA06iTcO8_w2J5Cae5T_0',
    appId: '1:314229576163:ios:dc2811e67d92fb844690d6',
    messagingSenderId: '314229576163',
    projectId: 'il-tris-pizzeria-ds',
    databaseURL: 'https://il-tris-pizzeria-ds-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'il-tris-pizzeria-ds.appspot.com',
    iosClientId: '314229576163-r3ru2c86ve9fa3k3grullnj6ijl5c3nl.apps.googleusercontent.com',
    iosBundleId: 'com.example.ilTrisManager',
  );

}